# --- https://www.playframework.com/documentation/2.6.x/Evolutions
# --- !Ups

create table "workflow" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "number_of_steps" int not null
);

create table "workflow_execution" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "workflow_id" bigint not null,
  "current_step_index" int not null,
  "creation_timestamp" timestamp default now() NOT NULL
);

create table "schedules" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "time_interval_ms" bigint not null,
  "workflowUuid" VARCHAR(100) not null,
  "last_trigger" bigint,
  "next_trigger" bigint
);

# --- !Downs

drop table "workflow" if exists;
drop table "workflow_execution" if exists;
drop table "schedules" if exists;
